apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task1
spec:
  params:
    - name: name
      type: string
  steps:
    - name: step1
      image: registry.access.redhat.com/ubi8/ubi
      script: |
        #!/bin/env bash
        echo "in pipeline $(params.name)"        
---
apiVersion: tekton.dev/v1
kind: Pipeline
spec:
  tasks:
    - name: pipepline-task1
      taskRef:
        name: task1       
        metadata: {}
        params:
          - default: output1
            name: name
            type: string
        matrix:
          params:
            - name: name
              value: ["output1", "output2"]         

 

            

