apiVersion: tekton.dev/v1
kind: PipelineRun
spec:
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/yogananth-subramanian/testrepo
    - name: revision
      value: main
    - name: pathInRepo
      value: integration-tests/pipeline-test.yaml


 

            

