apiVersion: tekton.dev/v1
metadata:
  name: pipepline-task1
kind: Pipeline
spec:
  tasks:
    - name: pipepline-task1
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/yogananth-subramanian/testrepo
          - name: revision
            value: main
          - name: pathInRepo
            value: integration-tests/test-task.yaml
      matrix:
        params:
          - name: name
            value: ["output1", "output2"]
  taskRunSpecs:
    - pipelineTaskName: pipepline-task1
      maxConcurrency: 1  # Limits the number of parallel task runs to 2                     
        

 

            

