apiVersion: tekton.dev/v1
metadata:
  name: pipepline1
kind: Pipeline
spec:
  params:
    - name: name
      default: ["output1", "output2"]
  tasks:
    - name: pipepline-task1
      params:
        - name: age
          value: output0   
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/yogananth-subramanian/testrepo
          - name: revision
            value: main
          - name: pathInRepo
            value: integration-tests/test-task-result.yaml
      matrix:
        params:
          - name: name
            value: $(params.name[*])
    - name: pipepline-task2
      runAfter:
        - pipepline-task1
      params:
        - name: myname
          value: $(tasks.pipepline-task1.results.TEST_TASK_OUTPUT[*])           
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/yogananth-subramanian/testrepo
          - name: revision
            value: main
          - name: pathInRepo
            value: integration-tests/test-task-result2.yaml

                                       
        

 

            

