apiVersion: tekton.dev/v1
metadata:
  name: pipepline1
kind: Pipeline
spec:
  params:
    - name: name
      default: ["output1", "output2"]
  tasks:
    - name: pipepline-task1
      params:
        - name: age
          value: output0   
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/yogananth-subramanian/testrepo
          - name: revision
            value: main
          - name: pathInRepo
            value: integration-tests/test-task-result.yaml
      matrix:
        params:
          - name: name
            value: $(params.name[*])
    - name: pipepline-task2
      runAfter:
        - pipepline-task1
      params:
        - name: age
          value: output1           
      matrix:
        params:
          - name: name
            value: $(tasks.pipepline-task1.results.TEST_TASK_OUTPUT[*])                     
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/yogananth-subramanian/testrepo
          - name: revision
            value: main
          - name: pathInRepo
            value: integration-tests/test-task-result.yaml
    - name: pipepline-task3
      runAfter:
        - pipepline-task1
      params:
        - name: myname
          value: $(tasks.pipepline-task1.results.TEST_TASK_OUTPUT[*])         
      taskSpec:
        params:
          - name: myname
            type: array
        steps:
          - name: step1
            image: registry.access.redhat.com/ubi8/ubi
            args: ["$(params.myname[*])"]
            script: |
              #!/bin/env bash
              printf "%s\n" "$@"
    - name: summarize-result
      runAfter:
        - pipepline-task3
      params:
        - name: krkn-result
          value: $(tasks.pipepline-task3.results.TEST_TASK_OUTPUT[*])         
      taskSpec:
        params:
          - name: krkn-result
            type: array
        steps:
          - name: step1
            image: registry.access.redhat.com/ubi8/ubi
            args: ["$(params.krkn-result[*])"]
            script: |
              #!/bin/env bash
              printf "%s\n" "$@"           

                                       
        

 

            

