apiVersion: tekton.dev/v1
kind: Pipeline
spec:
  tasks:
    - name: pipepline-task1
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/yogananth-subramanian/testrepo
          - name: revision
            value: main
          - name: pathInRepo
            value: integration-tests/test-task.yaml
      matrix:
        params:
          - name: name
            value: ["output1", "output2"]         
        

 

            

