apiVersion: tekton.dev/v1
metadata:
  name: pipepline1
kind: Pipeline
spec:
  tasks:
    - name: pipepline-task1
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/yogananth-subramanian/testrepo
          - name: revision
            value: main
          - name: pathInRepo
            value: integration-tests/test-task-result.yaml
      matrix:
        params:
          - name: name
            value: ["output1", "output2"]
    - name: pipepline-task2
      runAfter:
        - pipepline-task1   
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/yogananth-subramanian/testrepo
          - name: revision
            value: main
          - name: pathInRepo
            value: integration-tests/test-task-result.yaml
      matrix:
        params:
        - name: name
          value: $(tasks.pipepline.results.TEST_TASK_OUTPUT[*])                              
        

 

            

