---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: deploy-operator
spec:
  description: |
    An integration test which provisions an ephemeral Hypershift cluster and deploys an Operator
    bundle from a Konflux snapshot.
  params:
    - description: Snapshot of the application
      name: SNAPSHOT
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
    - description: Namespace where the the Operator bundle will be deployed.
      name: NAMESPACE
      default: default
      type: string
    - name: chaostest
      default: ["application-outages" ]
  tasks:
    - name: parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/integration-examples
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/test_metadata.yaml
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
    - name: provision-eaas-space
      runAfter:
        - parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: task/eaas-provision-space/0.1/eaas-provision-space.yaml
      params:
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)
    - name: provision-cluster
      runAfter:
        - provision-eaas-space
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/yogananth-subramanian/testrepo.git
          - name: revision
            value: main
          - name: pathInRepo
            value: integration-tests/task-provison-cluster.yaml
      params:
        - name: eaasSpaceSecretRef
          value: $(tasks.provision-eaas-space.results.secretRef)
    - name: deploy-app-krkn
      runAfter:
        - provision-cluster
      params:
        - name: bundleImage
          value: "$(tasks.parse-metadata.results.component-container-image)"
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
      matrix:
        params:
          - name: chaostest
            value: $(params.chaostest[*])                
      taskSpec:
        params:
          - name: bundleImage
            type: string
          - name: SNAPSHOT
            description: Expected output of the application endpoint
          - name: chaostest
            description: Namespace to deploy app to for testing                  
        results:
          - name: APP_URL
            description: APP URL
          - name: test_name
            description: Test name
          - name: reg_var
            description: Regression variable             
          - name: TEST_OUTPUT
            description: Test output
          - name: chaos_test_namespace
            description: Chaos test namespace                                  
        volumes:
          - name: credentials
            emptyDir: {}
        steps:
          - name: get-kubeconfig
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: clusterName
                value: "$(tasks.provision-cluster.results.clusterName)"
              - name: credentials
                value: credentials             
          - name: operator-sdk-run-bundle
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/yogananth-subramanian/testrepo.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: integration-tests/step-deploy-app.yaml
            params:
              - name: SNAPSHOT
                value: $(params.SNAPSHOT)
              - name: ocmSecretRef
                value: ocm
              - name: credentials
                value: credentials
              - name: chaostest
                value: $(params.chaostest)
    - name: run-krkn
      runAfter:
        - deploy-app-krkn
      params:
        - name: bundleImage
          value: "$(tasks.parse-metadata.results.component-container-image)"
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)        
      matrix:
        params:
        - name: chaostest
          value: $(tasks.deploy-app-krkn.results.chaos_test_namespace[*])
        - name: url
          value: $(tasks.deploy-app-krkn.results.APP_URL[*])                             
      taskSpec:
        params:
          - name: bundleImage
            type: string
          - name: chaostest
            type: string
          - name: SNAPSHOT
            description: Expected output of the application endpoint
          - name: url
            type: string              
        volumes:
          - name: credentials
            emptyDir: {}
        sidecars:
          - name: k6-perf
            image: grafana/k6
            env:
              - name: OCM_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: ocm
                    key: ocmtoken
            volumeMounts:
              - name: credentials
                mountPath: /workspace                                               
            script: |
              #!/usr/bin/env sh
              export
              echo "Transform result to json format"
              wget -O /tmp/ocm https://github.com/openshift-online/ocm-cli/releases/download/v0.1.65/ocm-linux-amd64
              chmod +x /tmp/ocm
              echo ${OCM_TOKEN}
              /tmp/ocm login --token=${OCM_TOKEN} --url=https://$(params.url)
              export BASE_URL=https://$(params.url)
              wget -O /tmp/script.js https://raw.githubusercontent.com/yogananth-subramanian/testrepo/refs/heads/main/integration-tests/rhtap-perf-k6-test.js
              echo -n `/tmp/ocm token`>/tmp/token
              k6 run /tmp/script.js
              cat /workspace/output.json
        steps:
          - name: get-kubeconfig
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: clusterName
                value: "$(tasks.provision-cluster.results.clusterName)"
              - name: credentials
                value: credentials
          - name: app-test
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/yogananth-subramanian/testrepo.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: integration-tests/step-deploy-krkn.yaml
            params:
              - name: KUBECONFIG
                value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
              - name: credentials
                value: credentials
              - name: chaostest
                value: $(params.chaostest)                             
