apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: krkn-perf-task
spec:
  params:
    - name: bundleImage
      type: string
    - name: SNAPSHOT
      description: Expected output of the application endpoint
      type: string
    - name: chaostest
      description: Namespace to deploy app to for testing
      type: string
    - name: eaasSpaceSecretRef
      type: string
    - name: clusterName
      type: string                           
  results:
    - name: APP_URL
      description: APP URL
    - name: test_name
      description: Test name
    - name: reg_var
      description: Regression variable             
    - name: TEST_OUTPUT
      description: Test output
    - name: chaos_test_namespace
      description: Chaos test namespace                                  
  volumes:
    - name: credentials
      emptyDir: {}
  steps:
    - name: get-kubeconfig
      ref:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
      params:
        - name: eaasSpaceSecretRef
          value: $(params.eaasSpaceSecretRef)
        - name: clusterName
          value: "$(params.clusterName)"
        - name: credentials
          value: credentials             
    - name: operator-sdk-run-bundle
      ref:
        resolver: git
        params:
          - name: url
            value: https://github.com/yogananth-subramanian/testrepo.git
          - name: revision
            value: main
          - name: pathInRepo
            value: integration-tests/step-deploy-app.yaml
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: ocmSecretRef
          value: ocm
        - name: credentials
          value: credentials
        - name: chaostest
          value: $(params.chaostest)