apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: provision-cluster
spec:
  results:
    - name: clusterName
      value: "$(steps.create-cluster.results.clusterName)"
  params:
    - name: eaasSpaceSecretRef
      type: string
  steps:
    - name: get-supported-versions
      ref:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: stepactions/eaas-get-supported-ephemeral-cluster-versions/0.1/eaas-get-supported-ephemeral-cluster-versions.yaml
      params:
        - name: eaasSpaceSecretRef
          value: $(params.eaasSpaceSecretRef)
    - name: pick-version
      ref:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: stepactions/eaas-get-latest-openshift-version-by-prefix/0.1/eaas-get-latest-openshift-version-by-prefix.yaml
      params:
        - name: prefix
          value: "$(steps.get-supported-versions.results.versions[0])."
    - name: create-cluster
      ref:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/eaas-create-ephemeral-cluster-hypershift-aws.yaml
      params:
        - name: eaasSpaceSecretRef
          value: $(params.eaasSpaceSecretRef)
        - name: version
          value: "$(steps.pick-version.results.version)"
        - name: instanceType	
          value: m5.large      