apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task2
spec:
  params:
    - name: myname
      type: string
  steps:
    - name: step1
      image: registry.access.redhat.com/ubi8/ubi
      script: |
        #!/bin/env bash
        echo "$(params.myname[*])"

