apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task1
spec:
  params:
    - name: name
      type: array
    - name: age
      type: string      
  results:
    - name: TEST_TASK_OUTPUT
      type: string          
  steps:
    - name: step1
      image: registry.access.redhat.com/ubi8/ubi
      script: |
        #!/bin/env bash
        echo "in pipeline $(params.name)"
        echo -n "$(params.name)" | tee $(results.TEST_TASK_OUTPUT.path)
